### ISSUE TITLE
Example of docker-compose.yml for swarm

### ISSUE THREAD

**Issue by garanews** [cakecloud/docker_swarm#1]
Hello,
I am trying to port some service from docker to swarm and need shared files.
Currently my docker-compose.yml is as follow:
```
version: "3"
volumes:
  media_path: {}
  symbols_path: {}
services:
  django: &django
    image: user/django:latest
    volumes:
      - media_path:/media
      - symbols_path:/symbols
  worker01:
    image: user/worker01:latest
    volumes:
      - media_path:/media
      - symbols_path:/symbols
```
It works on a docker but need to have couple of shared folder between containers and when passing on swarm I have some issue.
I would  avoid glusterfs, sshfs and also nfs (because need plugins to install in each docker node, or additional config)
I would try syncthings but not sure how to manage it.
Can you please help?
